name: Send mail
on: push

jobs:
  mail:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello world
        run: echo "Hello world"

      - name: Sending a mail
        if: always()  # Correct indentation and no double ${{ }} needed for if statement
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          body: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          to: jebashinba2001@gmail.com
          from: jebashinba2001@gmail.com # Correct format for the from field


